[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "False"